server:
  port: 8083

spring:
  datasource:
    url: ${CATALOG_SERVICE_DATASOURCE_URL:jdbc:postgresql://localhost:5434/catalog_service_db}
    username: catalog_service_user
    password: catalog_service_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG