server:
  port: 8083

spring:
  datasource:
    url: ${CATALOG_SERVICE_DATASOURCE_URL:jdbc:postgresql://localhost:5434/catalog_service_db}
    username: catalog_service_user
    password: catalog_service_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: catalog-service-group
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  topic:
    productCreated: product.product.created
    productUpdated: product.product.updated
    productDeleted: product.product.deleted

logging:
  level:
    org.hibernate.SQL: DEBUG