server:
  port: 8081
  max-http-header-size: 16384

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://${USER_SERVICE_HOST:localhost}:8080
          predicates:
            - Path=/api/v1/auth/**
        - id: seller-service
          uri: http://${USER_SERVICE_HOST:localhost}:8080
          predicates:
            - Path=/api/v1/sellers/**
        - id: user-service
          uri: http://${USER_SERVICE_HOST:localhost}:8080
          predicates:
            - Path=/api/v1/users/**
        - id: product-service
          uri: http://${PRODUCT_SERVICE_HOST:localhost}:8082
          predicates:
            - Path=/api/v1/products/**
        - id: catalog-service
          uri: http://${CATALOG_SERVICE_HOST:localhost}:8083
          predicates:
            - Path=/api/v1/catalog/**
        - id: inventory-service
          uri: http://${INVENTORY_SERVICE_HOST:localhost}:8084
          predicates:
            - Path=/api/v1/inventory/**
        - id: cart-service
          uri: http://${CART_SERVICE_HOST:localhost}:8085
          predicates:
            - Path=/api/v1/cart/**

jwt:
  secret: ${USER_SERVICE_JWT_SECRET:my-super-secret-key-1234567890123456}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG