server:
  port: 8081

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/auth/**
        - id: seller-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/sellers/**

jwt:
  secret: ${USER_SERVICE_JWT_SECRET:my-super-secret-key-1234567890123456}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG