server:
  port: 8080

spring:
  application:
    name: user-service

  datasource:
    url: ${USER_SERVICE_DATASOURCE_URL:jdbc:postgresql://localhost:5433/user_service_db}
    username: ${USER_SERVICE_DB_USERNAME:user_service_user}
    password: ${USER_SERVICE_DB_PASSWORD:user_service_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # change to validate or none in production
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      indent_output: true

  profiles:
    active: dev

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.ecommerce.userservice: DEBUG

jwt:
  secret: ${USER_SERVICE_JWT_SECRET:my-super-secret-key-1234567890123456}
  expirationMs: ${USER_SERVICE_JWT_EXPIRATION:3600000}  # 1 hour

---

# Additional Configs for Error Handling / Actuator (optional)

management:
  endpoints:
    web:
      exposure:
        include: "*"