server:
  port: 8082

spring:
  application:
    name: product-service
    
  datasource:
    url: ${PRODUCT_SERVICE_DATASOURCE_URL:jdbc:postgresql://localhost:5433/product_service_db}
    username: ${PRODUCT_SERVICE_DB_USERNAME:product_service_user}
    password: ${PRODUCT_SERVICE_DB_PASSWORD:product_service_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # change to validate or none in production
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
  kafka:
    bootstrap-servers: kafka:9092 # Kafka broker address
    consumer:
      group-id: product-service-group
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
          spring.deserializer.value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.UUIDSerializer  # Serializer for the key (UUID)
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  topic:
    sellerStatusUpdated: user.seller.status-updated
    productCreated: product.product.created
    productUpdated: product.product.updated
    productDeleted: product.product.deleted