server:
  port: 8085

spring:
  application:
    name: cart-service

  datasource:
    url: ${CART_SERVICE_DATASOURCE_URL:jdbc:postgresql://localhost:5436/cart_service_db}
    username: ${CART_SERVICE_DB_USERNAME:cart_service_user}
    password: ${CART_SERVICE_DB_PASSWORD:cart_service_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

